### ISSUE TITLE
Doesn't work on React-Native 0.26.2

### ISSUE THREAD

**Issue by sloanwolf** [tuanpmt/react-native-mqttjs#1]
Hey I came here from the README at https://github.com/tuanpmt/react-native-mqtt which has now changed saying to use https://github.com/eclipse/paho.mqtt.javascript

I tried playing around with react-native-mqttjs and paho.mqtt.javascript but can't get either working.

react-native-mqttjs doesn't work due to EventEmitter module.exports I think and paho.mqtt.javascript due to it not being a node module.

Do you have any examples of getting either of these to work?

**Comment by tuanpmt** [comment]
@sloanwolf Because react-native doesn't support localStorage, only need to add at begin off paho source. You can quick use [localstorage-memroy](https://www.npmjs.com/package/localstorage-memory) 

``` javascript
window = global || window;
window.localStorage = require('localstorage-memory');
```

and at the end of source:

``` javascript
export default Paho;
```

Usage:

``` javascript
import Paho  from './mqttws31';

var client = new Paho.MQTT.Client('localhost', Number(3000), "/mqtt", "test_client_id");

client.onConnectionLost = onConnectionLost;
client.onMessageArrived = onMessageArrived;

// connect the client
client.connect({onSuccess:onConnect});


// called when the client connects
function onConnect() {
  // Once a connection has been made, make a subscription and send a message.
  console.log("onConnect");
  client.subscribe("/World", {qos: 1});
  var message = new Paho.MQTT.Message("Hello");
  message.destinationName = "/World";
  message.qos = 1;
  client.send(message);
}

// called when the client loses its connection
function onConnectionLost(responseObject) {
  if (responseObject.errorCode !== 0) {
    console.log("onConnectionLost:"+responseObject.errorMessage);
  }
}

// called when a message arrives
function onMessageArrived(message) {
  console.log("onMessageArrived:"+message.payloadString);
}
```

**Comment by sloanwolf** [comment]
Thanks @tuanpmt that's what I ended up doing to get it working.

**Comment by sloanwolf** [comment]
Hey @tuanpmt I'm having a new problem. I want to use a Ruby MQTT gem to subscribe and publish to certain topics but they don't work with MQTT w/ WebSockets (it needs to connect to native MQTT broker, not via websockets and I can't find one that would support it). Even the Mosquitto Ruby binding, due to it only supporting mosquitto 1.3.1 but I need 1.4 for Websocket support.

My only options seem to be using websockets or to use your initial https://github.com/tuanpmt/react-native-mqtt client, but you say it's not production ready, why is that? I initially had it working but opted to use the JS clients due to your recommendation.

Another question is the difference between MQTT and WebSockets on mobile? It's my understanding that MQTT is lighter and more scalable than WebSockets, is that really the case?

**Comment by tuanpmt** [comment]
- Because `react-native-mqtt` using RTC bridge to bind from other native MQTT library to use with react-native, and I do not really spend much time on it
- Of course, MQTT over TCP will use less resources than over WebSocket, because it use native process. Meanwhile, WebSocket uses javascript interpreter. But don't worry, MQTT protocol takes very little resources to encoding and decoding, and Websocket in react-native is native implement

**Comment by sloanwolf** [comment]
Are you saying we should all just use Websockets with React-Native?

**Comment by tuanpmt** [comment]
yes

**Comment by ghost** [comment]
Hello @tuanpmt, how can someone solve the eventemitter issue in react native mqttjs?
